### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by maehw** [tobias-reese/timeular-api#1]
Hi there!

First, thank you for your code contributions. I'm trying to get get it running here. However, I have to admit that I am not a Python programmer (yet).

I got the example working by using
```
auth_api_instance = timeular_api.AuthenticationApi()
auth_api_key_and_api_secret = timeular_api.DeveloperSignInRequest(api_key='my_api_key', api_secret='my_api_secret')
```

I do get a token back. However, I fail when trying to continue... Can you please give another example?
What would a call of the TimeTrackingActivitiesApi to get_activities look like?

I can only get:
`HTTP response body: {"message":"Authorization token is invalid"}`

I the token relevant for a call? Nor using my API key neither my token works with the example code given in TimeTrackingActivitiesApi.md#get_activities.

```
configuration = timeular_api.Configuration()
configuration.api_key['Authorization'] = 'YOUR_API_KEY'
```

I'd be happy if you could help here.

Kinds regards,
Matthias

**Comment by tobias-reese** [comment]
Hey,

you have to extend your code like this:

```
api_response` = api_instance.developer_sign_in(api_key_and_api_secret=api_key_and_api_secret)

configuration = Configuration()
configuration.api_key['Authorization'] = api_response.token
configuration.api_key_prefix['Authorization'] = 'Bearer'

api_instance = timeular_api.TimeTrackingTimeEntriesApi(timeular_api.ApiClient(configuration))
api_response = api_instance.get_time_entries_in_range(stopped_after, started_before)
```

This should give you all time entries between given dates.

Best regards,
Tobias

**Comment by maehw** [comment]
Hey Tobias,

thanks for your help.

I've tried to use `get_time_entries_in_range` and failed again.

```
stopped_after = '2018-01-01T00:00:00.000'
started_before = '2018-12-31T23:59:59.999'
api_response = api_instance.get_time_entries_in_range(stopped_after, started_before)
```

Here's my traceback:

```
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    api_response = api_instance.get_time_entries_in_range(stopped_after, started_before)
  File "/home/matthias/repos/timeular-api/timeular_api/api/time_tracking__time_entries_api.py", line 351, in get_time_entries_in_range
    (data) = self.get_time_entries_in_range_with_http_info(stopped_after, started_before, **kwargs)  # noqa: E501
  File "/home/matthias/repos/timeular-api/timeular_api/api/time_tracking__time_entries_api.py", line 436, in get_time_entries_in_range_with_http_info
    collection_formats=collection_formats)
  File "/home/matthias/repos/timeular-api/timeular_api/api_client.py", line 322, in call_api
    _preload_content, _request_timeout)
  File "/home/matthias/repos/timeular-api/timeular_api/api_client.py", line 161, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/home/matthias/repos/timeular-api/timeular_api/api_client.py", line 233, in deserialize
    return self.__deserialize(data, response_type)
  File "/home/matthias/repos/timeular-api/timeular_api/api_client.py", line 272, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/matthias/repos/timeular-api/timeular_api/api_client.py", line 613, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/home/matthias/repos/timeular-api/timeular_api/api_client.py", line 250, in __deserialize
    for sub_data in data]
  File "/home/matthias/repos/timeular-api/timeular_api/api_client.py", line 272, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/matthias/repos/timeular-api/timeular_api/api_client.py", line 613, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/home/matthias/repos/timeular-api/timeular_api/api_client.py", line 272, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/matthias/repos/timeular-api/timeular_api/api_client.py", line 613, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/home/matthias/repos/timeular-api/timeular_api/api_client.py", line 264, in __deserialize
    return self.__deserialize_primitive(data, klass)
  File "/home/matthias/repos/timeular-api/timeular_api/api_client.py", line 544, in __deserialize_primitive
    return six.u(data)
  File "/usr/lib/python2.7/dist-packages/six.py", line 647, in u
    return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")
TypeError: decoding Unicode is not supported
```

I have tried to use single ticks, double quotes, ... stuff like u'...' - I don't really know what's going on - but it seems that it's related to string encoding. Can you please help out once more?

I don't know if it's relevant, but:
```
$ python --version
Python 2.7.12
```

Using another API call like the following works like a charm (I figured out the ID from the ics export):
```
time_entry_id = '987' # str | ID of a Time Entry, eg. `987`
api_instance.get_time_entry(time_entry_id)

```

Kind regards,
Matthias

**Comment by thopiekar** [comment]
Since Python2 is dead, we might consider closing this issue :)
